project_id = "egxwzmkdbymxooielidc"

[functions.search-places]
verify_jwt = false

[functions.search-instagram]
verify_jwt = false

[functions.search-linkedin]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.disparos-api]
verify_jwt = false

[functions.search-whatsapp-groups]
verify_jwt = false

[functions.maturador-api]
verify_jwt = false

[functions.crm-webhook]
verify_jwt = false

[functions.label-webhook]
verify_jwt = false