project_id = "egxwzmkdbymxooielidc"

[functions.search-places]
verify_jwt = false

[functions.search-instagram]
verify_jwt = false

[functions.search-linkedin]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.admin-api]
verify_jwt = false
